//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUSL_Medical_Center
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_test
    {
        public int col_one { get; set; }
        public string col_two { get; set; }
        public string col_three { get; set; }
        public string col_four { get; set; }
    }
}
